spring.application.name=Springboot-API-REST-VENTAS
server.port=${SERVER_PORT:8082}
spring.web.allow-cors=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.platform=mysql

spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html