name: Frontend CI/CD

on:
  push:
    branches: [ deploy ]
    paths: [ 'front_despacho/**', '.github/workflows/frontend.yml' ]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./front_despacho
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-despacho:latest
      - name: Deploy to EC2 Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_FRONT_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker rm -f frontend_despacho || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-despacho:latest
            sudo docker run -d --name frontend_despacho --restart unless-stopped -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/frontend-despacho:latest
